In [1]:
import pandas as pd

In [12]:
# - membaca file csv

In [3]:
dataFrame=pd.read_csv("csgo_round_snapshots.csv")

In [12]:
# - info dataset

In [13]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object
 4   bomb_planted                  122410 non-null  bool
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-null  float64
 13  ct_defuse_kits                122410 non-null  float64
 14  ct_players_alive              122410 non-null  float64
 15  t_players_alive               122410 non-null  float64
 16  ct_weapon_ak47                122410 non-null  float64
 17  t_weapon_ak47                 122410 non-null  float64
 18  ct_weapon_aug                 122410 non-null  float64
 19  t_weapon_aug                  122410 non-null  float64
 20  ct_weapon_awp                 122410 non-null  float64
 21  t_weapon_awp                  122410 non-null  float64
 22  ct_weapon_bizon               122410 non-null  float64
 23  t_weapon_bizon                122410 non-null  float64
 24  ct_weapon_cz75auto            122410 non-null  float64
 25  t_weapon_cz75auto             122410 non-null  float64
 26  ct_weapon_elite               122410 non-null  float64
 27  t_weapon_elite                122410 non-null  float64
 28  ct_weapon_famas               122410 non-null  float64
 29  t_weapon_famas                122410 non-null  float64
 30  ct_weapon_g3sg1               122410 non-null  float64
 31  t_weapon_g3sg1                122410 non-null  float64
 32  ct_weapon_galilar             122410 non-null  float64
 33  t_weapon_galilar              122410 non-null  float64
 34  ct_weapon_glock               122410 non-null  float64
 35  t_weapon_glock                122410 non-null  float64
 36  ct_weapon_m249                122410 non-null  float64
 37  t_weapon_m249                 122410 non-null  float64
 38  ct_weapon_m4a1s               122410 non-null  float64
 39  t_weapon_m4a1s                122410 non-null  float64
 40  ct_weapon_m4a4                122410 non-null  float64
 41  t_weapon_m4a4                 122410 non-null  float64
 42  ct_weapon_mac10               122410 non-null  float64
 43  t_weapon_mac10                122410 non-null  float64
 44  ct_weapon_mag7                122410 non-null  float64
 45  t_weapon_mag7                 122410 non-null  float64
 46  ct_weapon_mp5sd               122410 non-null  float64
 47  t_weapon_mp5sd                122410 non-null  float64
 48  ct_weapon_mp7                 122410 non-null  float64
 49  t_weapon_mp7                  122410 non-null  float64
 50  ct_weapon_mp9                 122410 non-null  float64
 51  t_weapon_mp9                  122410 non-null  float64
 52  ct_weapon_negev               122410 non-null  float64
 53  t_weapon_negev                122410 non-null  float64
 54  ct_weapon_nova                122410 non-null  float64
 55  t_weapon_nova                 122410 non-null  float64
 56  ct_weapon_p90                 122410 non-null  float64
 57  t_weapon_p90                  122410 non-null  float64
 58  ct_weapon_r8revolver          122410 non-null  float64
 59  t_weapon_r8revolver           122410 non-null  float64
 60  ct_weapon_sawedoff            122410 non-null  float64
 61  t_weapon_sawedoff             122410 non-null  float64
 62  ct_weapon_scar20              122410 non-null  float64
 63  t_weapon_scar20               122410 non-null  float64
 64  ct_weapon_sg553               122410 non-null  float64
 65  t_weapon_sg553                122410 non-null  float64
 66  ct_weapon_ssg08               122410 non-null  float64
 67  t_weapon_ssg08                122410 non-null  float64
 68  ct_weapon_ump45               122410 non-null  float64
 69  t_weapon_ump45                122410 non-null  float64
 70  ct_weapon_xm1014              122410 non-null  float64
 71  t_weapon_xm1014               122410 non-null  float64
 72  ct_weapon_deagle              122410 non-null  float64
 73  t_weapon_deagle               122410 non-null  float64
 74  ct_weapon_fiveseven           122410 non-null  float64
 75  t_weapon_fiveseven            122410 non-null  float64
 76  ct_weapon_usps                122410 non-null  float64
 77  t_weapon_usps                 122410 non-null  float64
 78  ct_weapon_p250                122410 non-null  float64
 79  t_weapon_p250                 122410 non-null  float64
 80  ct_weapon_p2000               122410 non-null  float64
 81  t_weapon_p2000                122410 non-null  float64
 82  ct_weapon_tec9                122410 non-null  float64
 83  t_weapon_tec9                 122410 non-null  float64
 84  ct_grenade_hegrenade          122410 non-null  float64
 85  t_grenade_hegrenade           122410 non-null  float64
 86  ct_grenade_flashbang          122410 non-null  float64
 87  t_grenade_flashbang           122410 non-null  float64
 88  ct_grenade_smokegrenade       122410 non-null  float64
 89  t_grenade_smokegrenade        122410 non-null  float64
 90  ct_grenade_incendiarygrenade  122410 non-null  float64
 91  t_grenade_incendiarygrenade   122410 non-null  float64
 92  ct_grenade_molotovgrenade     122410 non-null  float64
 93  t_grenade_molotovgrenade      122410 non-null  float64
 94  ct_grenade_decoygrenade       122410 non-null  float64
 95  t_grenade_decoygrenade        122410 non-null  float64
 96  round_winner                  122410 non-null  object
dtypes: bool(1), float64(94), object(2)
memory usage: 89.8+ MB

In [12]:
# -  dataset describe

In [14]:
dataFrame.describe()

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
count,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,...,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000,122410.000000
mean,97.886922,6.709239,6.780435,412.106568,402.714500,314.142121,298.444670,9789.023773,11241.036680,2.053901,...,1.853157,1.858100,1.540814,1.627146,1.001969,0.019819,0.048011,1.352095,0.027694,0.025750
std,54.465238,4.790362,4.823543,132.293290,139.919033,171.029736,174.576545,11215.042286,12162.806759,1.841470,...,1.772791,1.794473,1.737804,1.829147,1.458084,0.143933,0.227669,1.663246,0.169531,0.164162
min,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,54.920000,3.000000,3.000000,350.000000,322.000000,194.000000,174.000000,1300.000000,1550.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.910000,6.000000,6.000000,500.000000,500.000000,377.000000,334.000000,5500.000000,7150.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,166.917500,10.000000,10.000000,500.000000,500.000000,486.000000,468.000000,14600.000000,18000.000000,4.000000,...,3.000000,3.000000,3.000000,3.000000,2.000000,0.000000,0.000000,2.000000,0.000000,0.000000
max,175.000000,32.000000,33.000000,500.000000,600.000000,500.000000,500.000000,80000.000000,80000.000000,5.000000,...,7.000000,7.000000,6.000000,9.000000,5.000000,3.000000,3.000000,5.000000,3.000000,2.000000

In [12]:
# -  menampilkan 10 record pertama dari dataset

In [22]:
Dtypes = dataFrame.select_dtypes(include=['int','float'])
Dtypes.head(10)

,time_left,ct_score,t_score,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,...,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade
0,175.00,0.0,0.0,500.0,500.0,0.0,0.0,4000.0,4000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,156.03,0.0,0.0,500.0,500.0,400.0,300.0,600.0,650.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
2,96.03,0.0,0.0,391.0,400.0,294.0,200.0,750.0,500.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
3,76.03,0.0,0.0,391.0,400.0,294.0,200.0,750.0,500.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,174.97,1.0,0.0,500.0,500.0,192.0,0.0,18350.0,10750.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,114.97,1.0,0.0,500.0,500.0,500.0,0.0,1750.0,10550.0,5.0,...,3.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6,94.97,1.0,0.0,295.0,111.0,296.0,0.0,1700.0,5000.0,3.0,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,74.97,1.0,0.0,295.0,111.0,296.0,0.0,1700.0,5000.0,3.0,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,54.97,1.0,0.0,249.0,89.0,269.0,0.0,2300.0,2950.0,3.0,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,174.97,2.0,0.0,500.0,500.0,196.0,0.0,19800.0,23450.0,2.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
# -  menampilkan informasi jumlah record, jumlah attribute, nama attribute, jumlah attribute dengan tipe angka.

In [25]:
Dtypes = dataFrame.select_dtypes(include=['int','float'])
jumlah = {
    "jumlah_record" : dataFrame.count(),
    "jumlah_attribute" : len(dataFrame.columns),
    "nama_attribute" : dataFrame.columns,
    "jumlah_tipeAngka" : len(Dtypes.columns)
}

print(jumlah["jumlah_record"])
print("="*30)
print(jumlah["jumlah_attribute"])
print("="*30)
print(jumlah["nama_attribute"])
print("="*30)
print(jumlah["jumlah_tipeAngka"])

time_left                    122410
ct_score                     122410
t_score                      122410
map                          122410
bomb_planted                 122410
                              ...
ct_grenade_molotovgrenade    122410
t_grenade_molotovgrenade     122410
ct_grenade_decoygrenade      122410
t_grenade_decoygrenade       122410
round_winner                 122410
Length: 97, dtype: int64
==============================
97
==============================
Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev', 'ct_weapon_nova', 't_weapon_nova',
       'ct_weapon_p90', 't_weapon_p90', 'ct_weapon_r8revolver',
       't_weapon_r8revolver', 'ct_weapon_sawedoff', 't_weapon_sawedoff',
       'ct_weapon_scar20', 't_weapon_scar20', 'ct_weapon_sg553',
       't_weapon_sg553', 'ct_weapon_ssg08', 't_weapon_ssg08',
       'ct_weapon_ump45', 't_weapon_ump45', 'ct_weapon_xm1014',
       't_weapon_xm1014', 'ct_weapon_deagle', 't_weapon_deagle',
       'ct_weapon_fiveseven', 't_weapon_fiveseven', 'ct_weapon_usps',
       't_weapon_usps', 'ct_weapon_p250', 't_weapon_p250', 'ct_weapon_p2000',
       't_weapon_p2000', 'ct_weapon_tec9', 't_weapon_tec9',
       'ct_grenade_hegrenade', 't_grenade_hegrenade', 'ct_grenade_flashbang',
       't_grenade_flashbang', 'ct_grenade_smokegrenade',
       't_grenade_smokegrenade', 'ct_grenade_incendiarygrenade',
       't_grenade_incendiarygrenade', 'ct_grenade_molotovgrenade',
       't_grenade_molotovgrenade', 'ct_grenade_decoygrenade',
       't_grenade_decoygrenade', 'round_winner'],
      dtype='object')
==============================
94

In [12]:
# -  Tampilkan nilai dataset pada baris dimulai dengan 3 digit NIM akhir 
#    hingga data terakhir dan kolom ke 4 hingga kolom terakhir menggunakan ke 2 metode slice.

In [7]:
dataFrame.iloc[9:,4:]

,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,t_helmets,ct_defuse_kits,...,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
9,False,500.0,500.0,196.0,0.0,19800.0,23450.0,2.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
10,False,500.0,500.0,496.0,500.0,2200.0,1000.0,4.0,5.0,2.0,...,5.0,4.0,5.0,2.0,0.0,0.0,1.0,0.0,1.0,T
11,False,500.0,500.0,496.0,500.0,2200.0,1000.0,4.0,5.0,2.0,...,2.0,2.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,T
12,False,300.0,200.0,296.0,200.0,1200.0,50.0,2.0,2.0,1.0,...,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,T
13,False,116.0,126.0,187.0,179.0,1050.0,350.0,1.0,2.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122405,True,200.0,242.0,195.0,359.0,100.0,5950.0,2.0,4.0,1.0,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122406,False,500.0,500.0,95.0,175.0,11500.0,23900.0,1.0,2.0,1.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,T
122407,False,500.0,500.0,495.0,475.0,1200.0,6700.0,3.0,5.0,1.0,...,4.0,3.0,5.0,1.0,0.0,0.0,5.0,0.0,0.0,T
122408,False,500.0,500.0,495.0,475.0,1200.0,6700.0,3.0,5.0,1.0,...,5.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,0.0,T
122409,False,375.0,479.0,395.0,466.0,1100.0,7000.0,2.0,5.0,1.0,...,3.0,0.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,T

In [12]:
# -  Tampilkan jumlah nilai dari semua attribute yang bernilai object

In [27]:
dataFrame['round_winner'].value_counts()

round_winner
T     62406
CT    60004
Name: count, dtype: int64